name: Task Manager CI - Build and Test

on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: set nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: install package.json
        run: npm install

      - name: Run Testing
        run: npm test