name: Task Manager CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v5

      - name: 2. Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 3. Install dependencies
        run: npm install

      - name: 4. Build project
        run: npm run build

      - name: 5. Run Test1.js manually
        run: |
          output=$(node dist/Test1.js)
          echo "Output: $output"

          if [ "$output" -eq 0 ]; then
            echo "passed"
          else
            echo "failed"
            exit 1
          fi